name: Python Script

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python program
        run: python calc.py > output.txt

      - name: Show output
        run: cat output.txt
